openapi: 3.0.3
info:
  title: Stripe Payment Processor API
  version: "0.1"
paths:
  /api/stripe/processors/runs:
    post:
      summary: Trigger Stripe processor run
      description: Manually triggers Stripe payment import for a given time window.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                since:
                  type: string
                  format: date-time
                until:
                  type: string
                  format: date-time
                dryRun:
                  type: boolean
                  default: false
      responses:
        "202":
          description: Run accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  runId:
                    type: string
                  queued:
                    type: boolean
        "401":
          description: Auth required
  /api/reports/stripe-events/summary:
    get:
      summary: Aggregated Stripe events by product
      parameters:
        - in: query
          name: month
          schema:
            type: string
            pattern: '^\d{4}-\d{2}$'
          description: Optional YYYY-MM filter
      responses:
        "200":
          description: Summary list
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        eventKey:
                          type: string
                        name:
                          type: string
                        currency:
                          type: string
                        grossRevenue:
                          type: number
                        grossRevenuePln:
                          type: number
                        paymentsCount:
                          type: integer
  /api/reports/stripe-events/{eventKey}:
    get:
      summary: Detailed report for specific event
      parameters:
        - in: path
          name: eventKey
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Event details
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    type: object
                    properties:
                      name:
                        type: string
                      currency:
                        type: string
                      grossRevenue:
                        type: number
                      grossRevenuePln:
                        type: number
                      participants:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            amount:
                              type: number
                            currency:
                              type: string
                            amountPln:
                              type: number
                            paymentType:
                              type: string
  /api/reports/stripe-events/{eventKey}/export:
    get:
      summary: CSV export of participants for a Stripe event
      parameters:
        - in: path
          name: eventKey
          required: true
          schema:
            type: string
      responses:
        "200":
          description: CSV stream
          content:
            text/csv:
              schema:
                type: string
        "404":
          description: Event not found

